-   coco_json: /media/iaslab/data_bacchin/panizzolo/paniz_test_03_30_SINGLE.json
    output_jsonl: /media/iaslab/data_bacchin/panizzolo/paniz_test_03_30_SINGLE.vh_loop.jsonl
    dataset_id: paniz_test_03_30_single
    split: test
    description: "Panizzolo conveyor belt dataset with motor part instance annotations."
    annotation_source: human
    prompt_strategy: simple_prompt
    target_strategy: bbox_json_norm1000
    drop_empty: false
    include_categories: null  # null means keep all categories.Otherwise use, for example: [1, 2]

-   coco_json: /media/iaslab/data_bacchin/panizzolo/paniz_train_04_02_SINGLE.json
    output_jsonl: /media/iaslab/data_bacchin/panizzolo/paniz_train_04_02_SINGLE.vh_loop.jsonl
    dataset_id: panizzolo_train_04_02_single
    split: train
    description: "Panizzolo conveyor belt dataset with motor part instance annotations."
    annotation_source: human
    prompt_strategy: simple_prompt
    target_strategy: bbox_json_norm1000
    drop_empty: false
    include_categories: null  # null means keep all categories.Otherwise use, for example: [1, 2]

-   coco_json: /media/iaslab/data_bacchin/panizzolo/paniz_04_16_SINGLE.json
    output_jsonl: /media/iaslab/data_bacchin/panizzolo/paniz_04_16_SINGLE.vh_loop.jsonl
    dataset_id: panizzolo_train_04_16_single
    split: train
    description: "Panizzolo conveyor belt dataset with motor part instance annotations."
    annotation_source: human
    prompt_strategy: simple_prompt
    target_strategy: bbox_json_norm1000
    drop_empty: false
    include_categories: null  # null means keep all categories.Otherwise use, for example: