[workspace]
authors = ["Bacchin Alberto <bacchinalb@dei.unipd.it>, Riccardo Bastianello <riccardo.bastianello@it-robotics.it>"]
channels = ["pytorch", "nvidia", "conda-forge"]
name = "vh-loop"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.8"

# --- 1. GLOBAL BASE (Always Installed) ---
[dependencies]
python = "==3.13.12"
pip = "*"

[pypi-dependencies]
torch = { version = "==2.9.1", index = "https://download.pytorch.org/whl/cu128" }
torchvision = { version = "==0.24.1", index = "https://download.pytorch.org/whl/cu128" }
tqdm = "*"
PyYAML = "*"
hydra-core = ">=1.3"
omegaconf = ">=2.3"
argcomplete = ">=3.6.3"
pydantic = ">=2.0"
opencv-python = ">=4.8.1" # TO BE ADJUSTED
pytest = "*"
albumentations = ">=2.0.5" # TO BE ADJUSTED
matplotlib = ">=3.8.0" # TO BE ADJUSTED
transformers = "==5.7.0"

numpy = ">=2.3.1"
einops = ">=0.8.1" # TO BE ADJUSTED
xformers = ">=0.0.30" # TO BE ADJUSTED
qwen_vl_utils = ">=0.0.14"
#flash_attn = ">=2.7.4.post1" # Takes hours to compile, so we use a pre-built wheel instead.
#flash_attn = { url = "https://github.com/mjun0812/flash-attention-prebuild-wheels/releases/download/v0.7.16/flash_attn-2.8.3%2Bcu128torch2.9-cp313-cp313-linux_x86_64.whl" } #pre-built wheel for flash-attn, to speedup


accelerate = ">=0.30.0" # TO BE ADJUSTED
bitsandbytes = ">=0.41" # TO BE ADJUSTED
peft = ">=0.6" # TO BE ADJUSTED
trl = "==1.3.0"

pillow = ">=10.0" # TO BE ADJUSTED
pycocotools = ">=2.0" # TO BE ADJUSTED
datasets = "==4.8.5"


[target.linux-64.pypi-dependencies]
flash-attn = { url = "https://github.com/mjun0812/flash-attention-prebuild-wheels/releases/download/v0.7.16/flash_attn-2.8.3%2Bcu128torch2.9-cp313-cp313-linux_x86_64.whl" }
flash-linear-attention = ">=0.4.1" #to speedup qwen 3.5
causal-conv1d = ">=1.6.1" #to speedup qwen 3.5
triton = "==3.5.1"
liger-kernel = "==0.8.0" #TO BE ADJUSTED
post-training-toolkit = {git = "https://github.com/microsoft/post-training-toolkit.git"}
ollama="==0.6.2"


[target.win-64.pypi-dependencies]
flash-attn = { url = "https://huggingface.co/Wildminder/AI-windows-whl/resolve/main/flash_attn-2.8.3%2Bcu128torch2.9.1cxx11abiTRUE-cp313-cp313-win_amd64.whl" }


[tasks]
# 1. This task forces the isolated unsloth installation
install-unsloth = "pip install unsloth unsloth_zoo --no-deps"
# 2. A setup task that synchronizes the project and installs the package
setup = { depends-on = ["install-unsloth"] }

# --- PATH CONFIGURATION ---
# This ensures 'import src.model_core' works without 'pip install -e .'
[activation]
scripts = []

env = { PYTHONPATH = "${PYTHONPATH}:${PIXI_PROJECT_ROOT}" }

[target.win-64.activation]
env = { PYTHONPATH = "%PYTHONPATH%;%PIXI_PROJECT_ROOT%" }