finetune_vision_layers: True    # False if not finetuning vision layers
finetune_language_layers: True    # False if not finetuning language layers
finetune_attention_modules: True    # False if not finetuning attention layers
finetune_mlp_modules: True    # False if not finetuning MLP layers
r: 8    # The larger, the higher the accuracy, but might overfit
lora_alpha: 8    # Recommended alpha : :  r at least
lora_dropout: 0
bias: "none"
random_state: 3407
use_rslora: False    # We support rank stabilized LoRA
loftq_config: None    # And LoftQ