adapter: 'gemma4'
params:
  model_name_or_path: 'google/gemma-4-E2B-it'
  model_params:
    dtype: 'bfloat16'
    device_map: 'auto'
    trust_remote_code: true
    attn_implementation:
      sliding_attention: "flash_attention_2"
      full_attention: "sdpa"
  processor_params:
    max_soft_tokens: 140 #70, 140, 280, 560, or 1120 tokens, higher values preserve fine details but consumes more memory

