adapter: 'qwen3_5'
params:
  model_name_or_path: 'Qwen/Qwen3.5-2B'
  model_params:
    dtype: 'bfloat16'
    device_map: 'auto'
    trust_remote_code: true
    attn_implementation: 'flash_attention_2'
  processor_params:
    max_pixels: 802816 #1024x28x28

