training:
    -   id: cosmari_train_3000
        dataset_schema: conversational # conversational, prompt-completion
        jsonl_path: ${oc.env:DATA_PATH, /data}/canonical_datasets/cosmari_cosmari_train_s3000.canonical.jsonl
        root_override: ${oc.env:DATA_PATH, /data}
    -   id: warpD_train
        dataset_schema: conversational # conversational, prompt-completion
        jsonl_path: ${oc.env:DATA_PATH, /data}/canonical_datasets/warpD_warpD_train.canonical.jsonl
        root_override: ${oc.env:DATA_PATH, /data}
    -   id: zerowaste_train
        dataset_schema: conversational # conversational, prompt-completion
        jsonl_path: ${oc.env:DATA_PATH, /data}/canonical_datasets/zerowaste_zerowaste_train.canonical.jsonl
        root_override: ${oc.env:DATA_PATH, /data}
    -   id: zerowaste_val
        dataset_schema: conversational # conversational, prompt-completion
        jsonl_path: ${oc.env:DATA_PATH, /data}/canonical_datasets/zerowaste_zerowaste_val.canonical.jsonl
        root_override: ${oc.env:DATA_PATH, /data}
    -   id: paniz_04-02_SINGLE
        dataset_schema: conversational # conversational, prompt-completion
        jsonl_path: ${oc.env:DATA_PATH, /data}/canonical_datasets/panizzolo2_paniz_train_04_02_single.canonical.reviewed.jsonl
        root_override: ${oc.env:DATA_PATH, /data}

testing:
   -   id: paniz_03-30_SINGLE
       dataset_schema: conversational # conversational, prompt-completion
       jsonl_path: ${oc.env:DATA_PATH, /data}/canonical_datasets/panizzolo2_paniz_test_03_30_single.canonical.reviewed.jsonl
       root_override: ${oc.env:DATA_PATH, /data}
    # -   id: paniz_03-30_SINGLE
    #     dataset_schema: conversational # conversational, prompt-completion
    #     jsonl_path: ${oc.env:DATA_PATH, /data}/panizzolo/paniz_test_03_30_SINGLE.canonical_v2.jsonl
    #     root_override: ${oc.env:DATA_PATH, /data}/panizzolo
#    -   id: cosmari_test_1000
#        dataset_schema: conversational # conversational, prompt-completion
#        jsonl_path: ${oc.env:DATA_PATH, /data}/canonical_datasets/cosmari_cosmari_test_s1000.canonical.jsonl
#        root_override: ${oc.env:DATA_PATH, /data}
#    -   id: zerowaste_test
#        dataset_schema: conversational # conversational, prompt-completion
#        jsonl_path: ${oc.env:DATA_PATH, /data}/canonical_datasets/zerowaste_zerowaste_test.canonical.jsonl
#        root_override: ${oc.env:DATA_PATH, /data}
#    -   id: warpD_test
#        dataset_schema: conversational # conversational, prompt-completion
#        jsonl_path: ${oc.env:DATA_PATH, /data}/canonical_datasets/warpD_warpD_test.canonical.jsonl
#        root_override: ${oc.env:DATA_PATH, /data}
