training:
    -   id: paniz_04-02_SINGLE
        dataset_schema: conversational # conversational, prompt-completion
        jsonl_path: ${oc.env:DATA_PATH, /data}/panizzolo/paniz_train_04_02_SINGLE.canonical_v2.jsonl
        root_override: ${oc.env:DATA_PATH, /data}/panizzolo/

testing:
    -   id: paniz_03-30_SINGLE
        dataset_schema: conversational # conversational, prompt-completion
        jsonl_path: ${oc.env:DATA_PATH, /data}/panizzolo/paniz_test_03_30_SINGLE.canonical_v2.jsonl
        root_override: ${oc.env:DATA_PATH, /data}/panizzolo
