defaults:
  - /model: qwen3_5 # qwen3_5, gemma4
  - /experiment: test_exp
  - /dataset: panizzolo
  - /transform: paniz_s1000
  - /peft: lora
  - /trainer: qwen_sft_trainer # gemma4_sft_trainer, qwen_sft_trainer
  - /quantization: null # 4bit, 8bit, null
  - _self_

#run_id: gemma_ba_test #additional info to distinguish different runs, e.g., model name, dataset name, etc.
#log_level: info #debug, info, warning, error, critical, set to info or debug for more verbose logging
debug: true #when set to true, the code will run in debug mode, which may include additional logging, reduced dataset size, etc. Set to false for normal operation.
#debug_iters: 100 #number of iterations to run in debug mode, only effective when debug is true
#enable_pbar: false #whether to enable progress bar during training/evaluation, set to false to disable it
#
#save_every: 100 #save the intermediate results every N iterations, set to 0 to disable saving
#
#task: labelling #ident
exp: v3

exp_name: "${hydra:runtime.choices.model}_${hydra:runtime.choices.dataset}_${hydra:runtime.choices.peft}${strip_null:${hydra:runtime.choices.quantization}}_${exp}"

hydra:
  run:
    dir: ${oc.env:MODEL_PATH, /models}/vhloop/training/${exp_name}